languageCode = "en-us"
title = "Glog"
preserveTaxonomyNames = true

[author]
name = "TS"

[taxonomies]
category = "category"
game = "game"
platform = "platform"
rating = "rating"
tag = "tag"

[permalinks]
post = "/:year/:month/:day/:slug"

[blackfriday]
smartypants = false

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML","RSS"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[params]
now_playing = ["Middle-earth: Shadow of War"]
