name: BuildBranch

inputs:
  branch-ref:
    required: true
    type: string
  twitch-client-id:
    required: true
    type: string
  twitch-client-secret:
    required: true
    type: string
  output-path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: CheckoutBranch
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.branch-ref }}
        path: 'branch-checkout'

    - name: BuildBranchStaticSite
      shell: bash
      env:
        TWITCH_CLIENT_ID: ${{ inputs.twitch-client-id }}
        TWITCH_CLIENT_SECRET: ${{ inputs.twitch-client-secret }}
      run: |
        rm -rf BranchGlogGeneratorBuild
        dotnet build branch-checkout/GlogGenerator/GlogGenerator.csproj --configuration Release --output BranchGlogGeneratorBuild
        rm -rf ${{ inputs.output-path }}
        ./BranchGlogGeneratorBuild/GlogGenerator build -i branch-checkout -t BranchGlogGeneratorBuild/templates -u true --igdb-client-id $TWITCH_CLIENT_ID --igdb-client-secret $TWITCH_CLIENT_SECRET -h "https://tsuereth.com" -o ${{ inputs.output-path }}
