name: FetchLive

inputs:
  deploy-glog-private-key:
    required: true
    type: string
  output-path:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: DiffLiveSite
      shell: bash
      env:
        DEPLOY_GLOG_PRIVATE_KEY: ${{ inputs.deploy-glog-private-key }}
      run: |
        echo "$DEPLOY_GLOG_PRIVATE_KEY" > deploy-glog_id_rsa
        chmod 0600 deploy-glog_id_rsa
        rm -rf ${{ inputs.output-path }}
        rsync -vr --checksum --delete \
          -e "ssh -p 31771 -i deploy-glog_id_rsa -o StrictHostKeyChecking=no" \
          "deploy-glog@tsuereth.com:/var/www/tsuereth_web/glog/" \
          ${{ inputs.output-path }}/

    - name: CleanupKey
      if: ${{ always() }}
      shell: bash
      run: |
        rm -f deploy-glog_id_rsa
