name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  BuildSite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SetupDotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: RunTests
        run: |
          dotnet test GlogGenerator.Test/GlogGenerator.Test.csproj

      - name: BuildMain
        if: github.ref != 'refs/heads/main'
        uses: './.github/shared-steps/build-branch'
        with:
          branch-ref: 'refs/heads/main'
          twitch-client-id: ${{ secrets.TWITCH_CLIENT_ID }}
          twitch-client-secret: ${{ secrets.TWITCH_CLIENT_SECRET }}
          output-path: 'public-main'

      - name: FetchLive
        uses: './.github/shared-steps/fetch-live'
        with:
          deploy-glog-private-key: ${{ secrets.DEPLOY_GLOG_PRIVATE_KEY }}
          output-path: 'public-live'

      - name: RunGlogGenerator
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          OPTIONAL_COMPARE_TO_MAIN: ${{ github.ref != 'refs/heads/main' && '--compare-to branch-diff.txt=public-main' }}
          COMPARE_TO_LIVE: '--compare-to live-diff.txt=public-live'
        run: |
          rm -rf GlogGeneratorBuild
          dotnet build GlogGenerator/GlogGenerator.csproj --configuration Release --output GlogGeneratorBuild
          rm -rf public
          ./GlogGeneratorBuild/GlogGenerator build -i . -t GlogGeneratorBuild/templates -u true --igdb-client-id $TWITCH_CLIENT_ID --igdb-client-secret $TWITCH_CLIENT_SECRET -w true -h "https://tsuereth.com" -o public $OPTIONAL_COMPARE_TO_MAIN $COMPARE_TO_LIVE

      - name: ReportBranchDiff
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: 'branch-diff'
          path: 'branch-diff.txt'
          archive: false

      - name: ReportLiveDiff
        uses: actions/upload-artifact@v7
        with:
          name: 'live-diff'
          path: 'live-diff.txt'
          archive: false
