name: UpdateData

on:
  workflow_dispatch:
  # Run on a schedule to keep data updated even if there's no new content.
  schedule:
    - cron: '0 12 * * 5'

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SetupDotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: RunGlogGenerator
        env:
          TWITCH_CLIENT_ID: ${{ vars.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          rm -rf GlogGeneratorBuild
          dotnet build GlogGenerator/GlogGenerator.csproj --configuration Release --output GlogGeneratorBuild
          rm -rf public
          ./GlogGeneratorBuild/GlogGenerator build -i . -t GlogGeneratorBuild/templates -u true --igdb-client-id $TWITCH_CLIENT_ID --igdb-client-secret $TWITCH_CLIENT_SECRET -w true -h "https://tsuereth.com" -o public

      - name: SetupPullRequestValues
        run: |
          echo "GLOG_PR_BRANCH=autoupdate-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT" >> "$GITHUB_ENV"
          echo "GLOG_PR_DESCRIPTION=[skip ci] Automatically-updated content." >> "$GITHUB_ENV"

      - name: CreatePullRequest
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: GitHub <noreply@github.com>
          commit-message: ${{ env.GLOG_PR_DESCRIPTION }}
          title: ${{ env.GLOG_PR_DESCRIPTION }}
          body: ${{ env.GLOG_PR_DESCRIPTION }}
          branch: ${{ env.GLOG_PR_BRANCH }}
          base: main
