name: UpdateDataTest

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SetupDotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: TestGlogGenerator
        run: |
          dotnet test GlogGenerator.Test/GlogGenerator.Test.csproj

      - name: BuildGlogGenerator
        run: |
          rm -rf GlogGeneratorBuild
          dotnet build GlogGenerator/GlogGenerator.csproj --configuration Release --output GlogGeneratorBuild

      - name: UpdateDataAndBuildStaticSite
        env:
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        run: |
          rm -rf public
          ./GlogGeneratorBuild/GlogGenerator build -i . -t GlogGeneratorBuild/templates -u true --igdb-client-id jy5t8x2w2eqdc7bax2zx3rlne7eup4 --igdb-client-secret $TWITCH_CLIENT_SECRET -w true -h "https://tsuereth.com" -o public

      - name: CheckoutBase
        #if: github.event_name == 'pull_request'
        if: github.ref != 'refs/heads/main'
        uses: actions/checkout@v6
        with:
          #ref: github.base_ref
          ref: 'refs/heads/main'
          path: 'base-checkout'

      - name: DiffStaticSite
        #if: github.event_name == 'pull_request'
        if: github.ref != 'refs/heads/main'
        run: |
          rm -rf BaseGlogGeneratorBuild
          dotnet build base-checkout/GlogGenerator/GlogGenerator.csproj --configuration Release --output BaseGlogGeneratorBuild
          rm -rf base-public
          ./BaseGlogGeneratorBuild/GlogGenerator build -i . -t BaseGlogGeneratorBuild/templates -u true --igdb-client-id jy5t8x2w2eqdc7bax2zx3rlne7eup4 --igdb-client-secret $TWITCH_CLIENT_SECRET -w true -h "https://tsuereth.com" -o base-public
          diff -ur base-public public > public.diff

      - name: ReportDiff
        #if: github.event_name == 'pull_request'
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          path: 'public.diff'
