name: UpdateData

on:
  workflow_dispatch:
  # Run on a schedule to keep data updated even if there's no new content.
  schedule:
    - cron: '0 12 * * 5'

jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: SetupDotNet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: FetchLive
        uses: './.github/shared-steps/fetch-live'
        with:
          deploy-glog-private-key: ${{ secrets.DEPLOY_GLOG_PRIVATE_KEY }}
          output-path: 'public-live'

      - name: RunGlogGenerator
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          COMPARE_TO_LIVE: '--compare-to live-diff.txt=public-live'
        run: |
          rm -rf GlogGeneratorBuild
          dotnet build GlogGenerator/GlogGenerator.csproj --configuration Release --output GlogGeneratorBuild
          rm -rf public
          ./GlogGeneratorBuild/GlogGenerator build -i . -t GlogGeneratorBuild/templates -u true --igdb-client-id $TWITCH_CLIENT_ID --igdb-client-secret $TWITCH_CLIENT_SECRET -w true -h "https://tsuereth.com" -o public $COMPARE_TO_LIVE

      - name: ReportLiveDiff
        uses: actions/upload-artifact@v7
        with:
          name: 'live-diff'
          path: 'live-diff.txt'
          archive: false

      - name: AuthorizeGlogAutoUpdateApp
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.GLOG_AUTO_UPDATE_APP_ID }}
          private-key: ${{ secrets.GLOG_AUTO_UPDATE_PRIVATE_KEY }}

      - name: SetupPullRequestValues
        run: |
          echo "GLOG_PR_BRANCH=autoupdate-$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT" >> "$GITHUB_ENV"
          echo "GLOG_PR_DESCRIPTION=Automatically-updated content." >> "$GITHUB_ENV"

      - name: CreatePullRequest
        uses: peter-evans/create-pull-request@v8
        id: pull-request
        with:
          token: ${{ steps.app-token.outputs.token }}
          sign-commits: true
          commit-message: ${{ env.GLOG_PR_DESCRIPTION }}
          title: ${{ env.GLOG_PR_DESCRIPTION }}
          body: ${{ env.GLOG_PR_DESCRIPTION }}
          branch: ${{ env.GLOG_PR_BRANCH }}
          base: main
          add-paths: |
            content
            sitedataindex

      # TODO: Ideally we would PROMPT for deployment, using the diff above.
      # But workflow notification options don't really facilitate this kind
      # of on-success prompt! so just try the deployment automatically.
      - name: Deploy
        if: ${{ steps.pull-request.outputs.pull-request-url == '' }}
        env:
          DEPLOY_GLOG_PRIVATE_KEY: ${{ secrets.DEPLOY_GLOG_PRIVATE_KEY }}
        run: |
          echo "$DEPLOY_GLOG_PRIVATE_KEY" > deploy-glog_id_rsa
          chmod 0600 deploy-glog_id_rsa
          rsync -vrtL --checksum --omit-dir-times --cvs-exclude --delete \
            -e "ssh -p 31771 -i deploy-glog_id_rsa -o StrictHostKeyChecking=no" \
            public/* \
            "deploy-glog@tsuereth.com:/var/www/tsuereth_web/glog/"

      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -f deploy-glog_id_rsa
